name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GCC
      run: sudo apt install build-essential -y
    - uses: actions/checkout@v3
    - name: Compile
      run: make all
    - name: Test
      run: make test
